name: Blob storage website CI

on:
    push:
        branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set AZ Account
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |  
            az account set --subscription "ead81f63-964b-4a53-942e-7a3448c0ff58"
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name staysydstaticweb01 --auth-mode key -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "my-cdn-profile-webdev" --name "cmdev01" --resource-group "arg-cloudresumechallenge"
    # Azure logout 
    - name: logout
      run: |
            az logout
